#!/usr/bin/env python3
"""
Step 3b Generate one HADDOCK3 TOML config per representative (N_CLUSTER total).

Each config docks one peptide conformer against the receptor using the
pre-computed AIR (Ambiguous Interaction Restraint). Configs are written to haddock3_runs/.

HADDOCK3(High Ambiguity Driven protein-protein DOCKing) pipeline used:
 -topoaa, Tology and coordinates. Reads the input PDBs and builds the molecular topology using 
  CNS: assigns atom types, bonds, angles, dihedrals, and generates missing hydrogen atoms. CNS uses the PARALLHDG 
  force field with OPLS non-bonded parameters.
 -rigidbody, Generates RIGID_SAMPLING docking solutions by treating both molecules as rigid bodies. The 
  peptide is randomly placed around the receptor and then energy-minimised while satisfying the AIR restraints.
 -seletop, Selects the SELETOP_N best-scoring poses from rigidbody to pass forward.
 -flexref, Runs simulated annealing with CNS. Now the interface residues are allowed to move: 
  first the backbone at the interface becomes flexible, then sidechains. 
  The AIR restraints are still active. This is where the peptide adapts its conformation to fit the receptor binding site.
 -emref, Final energy minimisation of each pose in implicit solvent.
 -clustfcc, Groups the emref poses by structural similarity using FCC: two poses are similar if they share a high 
  fraction of the same receptor-peptide atom contacts. Doesn't require superposition. 
  The fraction_cutoff = 0.60 means two poses must share 60% of contacts to be in the same cluster.
 -seletopclusts, Picks the best-scoring pose from each cluster (up to {top_models} per cluster).

 
Usage:
  cd pipeline/03_haddock
  python generate_haddock3_configs.py
  # Configs ready for slurm/03_haddock_array.slurm
"""

import os, glob

HADDOCK_INPUTS = os.path.abspath("haddock_inputs")
RUN_ROOT       = os.path.abspath("haddock3_runs")
AMBIG_TBL      = os.path.join(HADDOCK_INPUTS, "ambig.tbl")
RECEPTOR_PDB   = os.path.join(HADDOCK_INPUTS, "receptor.pdb")
NCORES         = 16    # CPU cores per HADDOCK3 run (match SLURM --cpus-per-task)
RIGID_SAMPLING = 2000  # rigid-body structures
SELETOP_N      = 300   # pass to semi-flexible refinement

os.makedirs(RUN_ROOT, exist_ok=True)

peptide_pdbs = sorted(glob.glob(os.path.join(HADDOCK_INPUTS, "peptide_rep_*.pdb")))
if not peptide_pdbs:
    raise FileNotFoundError(
        f"No peptide_rep_*.pdb found in {HADDOCK_INPUTS}.\n"
        "Run prepare_haddock_inputs.py first."
    )

toml_files = []

for pdb in peptide_pdbs:
    rep_id   = os.path.basename(pdb).replace("peptide_rep_", "").replace(".pdb", "")
    run_dir  = os.path.join(RUN_ROOT, f"run_rep_{rep_id}")
    toml_path = os.path.join(RUN_ROOT, f"run_rep_{rep_id}.toml")

    toml = f"""\
# HADDOCK3 run – representative {rep_id}
# Generated by generate_haddock3_configs.py

run_dir  = "{run_dir}"
mode     = "local"
ncores   = {NCORES}

molecules = [
    "{RECEPTOR_PDB}",
    "{os.path.abspath(pdb)}"
]

# ── Topology ─────────────────────────────────────────────────────────────────
[topoaa]
autohis = true

# ── Rigid-body docking ────────────────────────────────────────────────────────
[rigidbody]
sampling    = {RIGID_SAMPLING}
ambig_fname = "{AMBIG_TBL}"
w_vdw       = 0.01
w_elec      = 0.0
w_desolv    = 0.0
w_air       = 0.1

# ── Select top {SELETOP_N} for refinement ─────────────────────────────────────
[seletop]
select = {SELETOP_N}

# ── Semi-flexible refinement ─────────────────────────────────────────────────
[flexref]
ambig_fname = "{AMBIG_TBL}"
w_vdw       = 1.0
w_elec      = 0.2
w_desolv    = 1.0
w_air       = 0.1

# ── Energy minimisation ───────────────────────────────────────────────────────
[emref]
ambig_fname = "{AMBIG_TBL}"

# ── FCC clustering ────────────────────────────────────────────────────────────
[clustfcc]
clust_cutoff   = 0.60
min_population = 4

# ── Extract top 4 models per cluster ─────────────────────────────────────────
[seletopclusts]
top_models = 4
"""

    with open(toml_path, "w") as f:
        f.write(toml)

    toml_files.append(toml_path)
    print(f"  rep_{rep_id} → {toml_path}")

# Write a plain list of TOML files (consumed by the SLURM array script)
list_file = os.path.join(RUN_ROOT, "toml_list.txt")
with open(list_file, "w") as f:
    f.write("\n".join(toml_files) + "\n")

print(f"\n{len(toml_files)} TOML configs written.")
print(f"TOML list → {list_file}")
print(f"\nNext: sbatch slurm/03_haddock_array.slurm")
